major_version: 0
tables:
  # MySQL uses database.table format (not schema.table like PostgreSQL)
  primary_db.users:
    name: FakeName
    email:
      type: Template
      template: '{{.name | slugify}}@example.com'
    password:
      type: PasswordArgon2id
      cleartext: 'staging'  # same password for all users
