version: v1
tables:
  public.users:
    name: FakeName
    email:
      type: Template
      template: '{{.name | slugify}}@example.com'
    password:
      type: PasswordArgon2id
      cleartext: 'staging'  # same password for all users
