services:
  pg_primary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-pg_primary-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: source_db
    ports:
      - "5432:5432"

  pg_replica:
    image: postgres:15
    container_name: demo-pg_replica-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: replica_db
    ports:
      - "5433:5432"
